### ISSUE TITLE
Something wrong with 64-bit compilation. 

### ISSUE THREAD

**Issue by sarslander** [gpolak/FGTranslator#11]
Great FGTranslator, but doesn't compile with 64-bit architecture. Is it possible to fix it?

**Comment by gpolak** [comment]
@sarslander what kind of error are you seeing? The demo supports arm64, armv7, and armv7s architectures. Can you run it?

**Comment by sarslander** [comment]
if I set 'Build for active architecture' to NO
 Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TMCache", referenced from:
      objc-class-ref in FGTranslator.o
  "_OBJC_CLASS_$_AFXMLParserResponseSerializer", referenced from:
      objc-class-ref in FGTranslateRequest.o
  "_OBJC_CLASS_$_AFJSONResponseSerializer", referenced from:
      objc-class-ref in FGTranslateRequest.o
  "_OBJC_CLASS_$_AFHTTPRequestOperation", referenced from:
      objc-class-ref in FGTranslateRequest.o
  "_OBJC_CLASS_$_SVProgressHUD", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sarslander** [comment]
If I set 'Build Active architecture Only' to YES, the demo works fine

**Comment by gpolak** [comment]
'Build Active architecture Only' is set to YES for Debug and NO for Release. Release builds should work fine. Is there a reason why you're changing the YES setting for Debug?

**Comment by sarslander** [comment]
reinstall pod and the problem gone. Thanks for the great library!

**Comment by gpolak** [comment]
Thanks @sarslander , glad it works. :)

Looks like Cocoapods changes the active architecture when installing pods: http://guides.cocoapods.org/using/troubleshooting.html#running-into-build-failures-after-migrating-to-xcode-5-and-cocoapods-0.25.0. Search for "ONLY_ACTIVE_ARCH" in the link above if you're curious.
