### ISSUE TITLE
How can i translate Speech to Text?

### ISSUE THREAD

**Issue by sohilmultani** [gpolak/FGTranslator#21]
I have Create Application to translate text-to-text , text-to-speech.
Now I want to translate Speech-to-speech and Speech-to-text.

How can i use your demo to translate Speech-to-text and Speech-to-Speech ?
How can i send audio in chunks to microsoft API?
In Objective-C

Please Help me.

**Comment by gpolak** [comment]
Sorry, this is a pure text-text API only.
