### ISSUE TITLE
Bing Translate doesn't work

### ISSUE THREAD

**Issue by lbrndnr** [gpolak/FGTranslator#7]
I use Bing Translate as it is free(er ;)) than Google.
When I try to translate "Bonjour" I get the following "AFNetworking" error: 
<code>Error Domain=AFNetworkingErrorDomain Code=-1011 "Request failed: bad request (400)" UserInfo=0xa0655c0 {NSErrorFailingURLKey=http://api.microsofttranslator.com/V2/Http.svc/Translate?to=en&text=Bonjour, NSLocalizedDescription=Request failed: bad request (400), NSUnderlyingError=0xa078930 "Request failed: unacceptable content-type: text/html", AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0xa06a070> { URL: http://api.microsofttranslator.com/V2/Http.svc/Translate?to=en&text=Bonjour } { status code: 400, headers {
    "Content-Length" = 265;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Sun, 24 Aug 2014 11:26:57 GMT";
    "X-MS-Trans-Info" = ";cid=1146.V2_Rest.Translate.2B05ADCC";
} }}</code>

Thanks for any help

EDIT: Noticed that only translating doesn't work. Detecting and the supported languages request work just fine.

**Comment by doriansgithub** [comment]
Hi gpolak, can you help me fix this issue?  It's the same issue, but since everything has been moved to the MS Azure portal, I can't seem to be able to find the "secret".  Is it the Account Name?  Thanks!

**Comment by gerchicov-bp** [comment]
it seems part for Bing should be updated

**Comment by doriansgithub** [comment]
I think Microsoft closed the entire thing forcing people to open an azure account, which is not free, and rewriting the code for azure.
