### ISSUE TITLE
Cache doesn't take source into account

### ISSUE THREAD

**Issue by edekhayser** [gpolak/FGTranslator#9]
The cached result does not take into account the target language of the translation. For example, if I translate the string "Hello" to Spanish, the cache stores "Hola". Then, if I try to retranslate it into French, it will still say "Hola" because the cache does not store the language it is translated into. I will see if there is a way to fix this issue myself, but for now, I have the caching code in FGTranslator.m commented out.

**Comment by gpolak** [comment]
Thanks for spotting this Evan! I merged your fix and released a new version (1.1.1) to CocoaPods.
